pipeline { 
    agent any
    tools { maven 'maven 3.6.3'
    } 

    stages{ 
        stage('build'){ 
            steps{ 
                echo 'Compiling worker app' 
                dir('worker'){ 
                  sh 'mvn compile' 
                } 
            } 
        } 
        stage('test'){ 
            steps{ 
                echo 'running unit tests on worker app' 
            } 
        } 
        stage('package'){ 
            steps{ 
                echo 'packaging worker app into a jarfile'
            } 
        } 
    }
    post{ 
        always{ 
            echo 'Building multibranch pipeline for worker is completed'
    }
  }
}
